# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region = "us-east-1"
  default_tags {
    tags = {
      Project     = "finnow-drx"
      Owner       = "finops-team"
      ManagedBy   = "Terragrunt"
      Environment = "Production"
      DR_Strategy = "Warm-Standby"
      Compliance  = "PCI-DSS"
    }
  }
}
